before:
  hooks:
    - go mod download
builds:
  - binary: acg
    main: ./acg/main.go
    ldflags:
      - -s -w
      - -X atcoder-gli/cmd.packageVersion={{.Version}}
      - -X atcoder-gli/cmd.packageCommit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
