before:
  hooks:
    - go mod download
builds:
  - main: ./acg/main.go
    ldflags:
      - -s -w
      - -X atcoder-gli/cmd.packageVersion={{.Version}}
      - -X atcoder-gli/cmd.packageCommit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - format: binary
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
